

services:
  goliath:
    image: run-agent-zero
    container_name: goliath
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCH: main
    volumes:
      - ../..:/app
      - ../../data/training:/data/training
    ports:
      - "3022:22"
      - "8080:80"
      - "9000-9009:9000-9009"
    tty: true
    stdin_open: true
